### ISSUE TITLE
Want to Give Thanks via Packer.nvim

### ISSUE THREAD

**Issue by chr0n1x** [jsongerber/thanks.nvim#2]
Hello, saw this on reddit and frankly love the idea. Thank you!

I use [Packer.nvim](https://github.com/wbthomason/packer.nvim)

Personally I'd prefer to star plugins when I run `PackerSync`, not sure if others in the community would have preferences that make more sense though.

**Comment by jsongerber** [comment]
Thanks for the message, I'll investigate how Packer works and if they provide an api to get the plugin list and some kind of event where I could hook.
It will probably take a few days as I never used Packer and don't have a lot of free time but I'll get back to you!

**Comment by jsongerber** [comment]
So I installed packer today and updated thanks.nvim to be compatible with it, could you give it a try?
I updated the readme with installation instructions for packer, and added a `star_on_install` config option.
Since I don't use packer as a daily basis I'm not 100% sure that I'm not missing some Packer behavior, but if something doesn't work as intended please feel free to open an other issue.
